### PR TITLE
Updated descriptions in app, added docstrings, edited link mixup in readme.md

### PR DESCRIPTION
**Pull request by evelynmoorhouse**

### CODE REVIEW

**Comment by evelynmoorhouse** [comment]
Hey Serge, the deleted procfile and requirement txt files were old commits from last Saturday when I tried to deploy, I was deleting them from my master branch, and not the milestone2 branch. My repo with all these changes still has the procfile and requirement txt file in the milestone 2 branch with the same requirements and formatting that you implemented in deployment. So I'm 99% sure that if you merge than the files won't be deleted. If they are we can just revert to a previous commit

**Comment by evelynmoorhouse** [comment]
Actually no I think you're right sorry

**Comment by evelynmoorhouse** [comment]
I'll add the procfile and requirements file back

**Comment by evelynmoorhouse** [comment]
Hey Serge, in PR #29 those same commits about deleting the procfile were already merged with the main repo (you can check the commit number). I don't know why they appear again, but I think since they were already merged successfully and didn't end up deleting the files then they should be okay. Let me know your thoughts. I'm stepping out for about an hour but can look after

**Comment by pokrovskyy** [comment]
Ok I'm merging that in now, and we'll re-add them later in case they indeed get deleted. I think this might be due to the fact we played with deployment, but maybe it's just the references

**Comment by pokrovskyy** [comment]
So apparently it did delete them from the repository - can you add them back when you are around? This is non-critical don't worry (milestone2 branch is separate and safe )

**Comment by evelynmoorhouse** [comment]
Yes I can, just about to head out, but before the merge those files weren't in the master repo, I actually double checked to make sure. Do we need them there since we deployed from the milestone2? Happy to add them back of course, I just assumed they didn't need to be in the master.

**Comment by pokrovskyy** [comment]
Yes we will need them eventually, although we added them specifically for milestone3 branch, I merged them back to master because we will actually need them all when we create milestone3 etc.

**Comment by evelynmoorhouse** [comment]
Ahh thank you Serg! sorry I needed to step out right at 2:30 otherwise I would have done it then since I was the one who removed them. Once again appreciate the solve and sorry for the mix up!

**Pull request merged**
